/*
 * Public zz9k.library identity and LVO layout.
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 */

#ifndef ZZ9K_LIBRARY_VECTORS_H
#define ZZ9K_LIBRARY_VECTORS_H

#define ZZ9K_LIBRARY_NAME "zz9k.library"
#define ZZ9K_LIBRARY_VERSION 2
#define ZZ9K_LIBRARY_REVISION 30
#define ZZ9K_LIBRARY_ID_STRING "zz9k.library 2.29 (30.08.2026)"

#define ZZ9K_LIBRARY_MIN_REVISION_CALL_ASYNC_BATCH_MSG 1
#define ZZ9K_LIBRARY_MIN_REVISION_CANCEL_ASYNC 2
#define ZZ9K_LIBRARY_MIN_REVISION_WAIT_ASYNC 3
#define ZZ9K_LIBRARY_MIN_REVISION_WAIT_ASYNC_BATCH 4
#define ZZ9K_LIBRARY_MIN_REVISION_ACCEL_JOB_WRAPPERS 5
#define ZZ9K_LIBRARY_MIN_REVISION_CRYPTO_HASH_BATCH 6
#define ZZ9K_LIBRARY_MIN_REVISION_CRYPTO_STREAM 7
#define ZZ9K_LIBRARY_MIN_REVISION_CRYPTO_STREAM_BATCH 8
#define ZZ9K_LIBRARY_MIN_REVISION_CRYPTO_AEAD 9
#define ZZ9K_LIBRARY_MIN_REVISION_CRYPTO_AEAD_BATCH 10
#define ZZ9K_LIBRARY_MIN_REVISION_SURFACE_OPS 11
#define ZZ9K_LIBRARY_MIN_REVISION_DIAG_SURFACES 12
#define ZZ9K_LIBRARY_MIN_REVISION_IMAGE_SESSIONS 13
#define ZZ9K_LIBRARY_MIN_REVISION_SCALE_IMAGE_CLIPPED 14
#define ZZ9K_LIBRARY_MIN_REVISION_TYPED_IMAGE_DECODE 15
#define ZZ9K_LIBRARY_MIN_REVISION_IRQ_WAIT 16
#define ZZ9K_LIBRARY_MIN_REVISION_EVENT_DISPATCHER 17
#define ZZ9K_LIBRARY_MIN_REVISION_AUDIO_DECODE 21
#define ZZ9K_LIBRARY_MIN_REVISION_AUDIO_STREAM 22
#define ZZ9K_LIBRARY_MIN_REVISION_CRYPTO_KX 23
#define ZZ9K_LIBRARY_MIN_REVISION_CRYPTO_VERIFY 24
#define ZZ9K_LIBRARY_MIN_REVISION_AUDIO_PLAYBACK 25
/* ZZ9KAllocShared honors ZZ9K_ALLOC_HOST_WINDOW / ZZ9K_ALLOC_CARD_ONLY
 * (no new vector; gate on ZZ9K_CAP_HOST_WINDOW_HEAP for firmware support) */
#define ZZ9K_LIBRARY_MIN_REVISION_ALLOC_FLAGS 26
/* Request validation accepts the resumable AUDIO_STREAM_FEED_DRAIN flag
 * (no new vector; firmware support is gated by the matching capability). */
#define ZZ9K_LIBRARY_MIN_REVISION_AUDIO_STREAM_DRAIN 27
#define ZZ9K_LIBRARY_MIN_REVISION_QUERY_PALETTE 28

#define ZZ9K_LVO_OPEN (-6)
#define ZZ9K_LVO_CLOSE (-12)
#define ZZ9K_LVO_EXPUNGE (-18)
#define ZZ9K_LVO_EXTFUNC (-24)

#define ZZ9K_LVO_QUERY_CAPS (-30)
#define ZZ9K_LVO_QUERY_SERVICE (-36)
#define ZZ9K_LVO_PING (-42)
#define ZZ9K_LVO_CALL (-48)
#define ZZ9K_LVO_CALL_ASYNC (-54)
#define ZZ9K_LVO_CALL_ASYNC_BATCH (-60)
#define ZZ9K_LVO_POLL (-66)
#define ZZ9K_LVO_ALLOC_SHARED (-72)
#define ZZ9K_LVO_FREE_SHARED (-78)
#define ZZ9K_LVO_MEM_FILL (-84)
#define ZZ9K_LVO_MEM_COPY (-90)
#define ZZ9K_LVO_ALLOC_SURFACE (-96)
#define ZZ9K_LVO_ALLOC_SURFACE_EX (-102)
#define ZZ9K_LVO_FREE_SURFACE (-108)
#define ZZ9K_LVO_MAP_FRAMEBUFFER_SURFACE (-114)
#define ZZ9K_LVO_SCALE_IMAGE (-120)
#define ZZ9K_LVO_READ_DIAG (-126)
#define ZZ9K_LVO_CALL_ASYNC_MSG (-132)
#define ZZ9K_LVO_CALL_ASYNC_BATCH_MSG (-138)
#define ZZ9K_LVO_CANCEL_ASYNC (-144)
#define ZZ9K_LVO_WAIT_ASYNC (-150)
#define ZZ9K_LVO_WAIT_ASYNC_BATCH (-156)
#define ZZ9K_LVO_DECODE_IMAGE (-162)
#define ZZ9K_LVO_CRYPTO_HASH (-168)
#define ZZ9K_LVO_CRYPTO_HASH_BATCH (-174)
#define ZZ9K_LVO_CRYPTO_STREAM (-180)
#define ZZ9K_LVO_CRYPTO_STREAM_BATCH (-186)
#define ZZ9K_LVO_CRYPTO_AEAD (-192)
#define ZZ9K_LVO_CRYPTO_AEAD_BATCH (-198)
#define ZZ9K_LVO_FILL_SURFACE (-204)
#define ZZ9K_LVO_COPY_SURFACE (-210)
#define ZZ9K_LVO_IMAGE_SESSION_BEGIN (-216)
#define ZZ9K_LVO_IMAGE_SESSION_FEED (-222)
#define ZZ9K_LVO_IMAGE_SESSION_CLOSE (-228)
#define ZZ9K_LVO_SCALE_IMAGE_CLIPPED (-234)
#define ZZ9K_LVO_DECODE_JPEG (-240)
#define ZZ9K_LVO_DECODE_PNG (-246)
#define ZZ9K_LVO_DECODE_GIF (-252)
#define ZZ9K_LVO_DECODE_MP3 (-258)
#define ZZ9K_LVO_AUDIO_STREAM_BEGIN (-264)
#define ZZ9K_LVO_AUDIO_STREAM_FEED (-270)
#define ZZ9K_LVO_AUDIO_STREAM_READ (-276)
#define ZZ9K_LVO_AUDIO_STREAM_CLOSE (-282)
#define ZZ9K_LVO_CRYPTO_KEY_EXCHANGE (-288)
#define ZZ9K_LVO_CRYPTO_VERIFY (-294)
#define ZZ9K_LVO_AUDIO_STREAM_PLAY (-300)
#define ZZ9K_LVO_AUDIO_STREAM_STOP (-306)
/* The historical palette branch allocated -300, which current master uses for
 * AUDIO_STREAM_PLAY. Taking the next free vector instead; merging that branch
 * as-is would have aliased two calls onto one entry. */
#define ZZ9K_LVO_QUERY_PALETTE (-312)

#define ZZ9K_LVO_FUNCTION_COUNT 48

#endif /* ZZ9K_LIBRARY_VECTORS_H */
